set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/nerdcommenter'

Plugin 'Valloric/MatchTagAlways'
Plugin 'Valloric/YouCompleteMe'

Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-bundler'

Plugin 'mattn/emmet-vim'

Plugin 'kien/ctrlp.vim'

Plugin 'vim-ruby/vim-ruby'

Plugin 'flazz/vim-colorschemes'

Plugin 'Townk/vim-autoclose'

Plugin 'alvan/vim-closetag'

call vundle#end()            " required
filetype plugin indent on    " required
filetype plugin on

set relativenumber
set clipboard=unnamedplus
syntax on
colorscheme blazer

map <F3> :NERDTreeToggle<CR>
map <F2> :CtrlPClearAllCaches<CR>

"tab settings
set mouse=a
set tabstop=2
set shiftwidth=2
set expandtab
filetype plugin indent on

set autoread

" Copy paste configurations
vmap <C-c> "+yi
vmap <C-x> "+c
vmap <C-v> c<ESC>"+p
imap <C-v> <C-r><C-o>+

" YouCompleteMe and closetag configurations
let g:ycm_global_ycm_extra_conf = "~/.vim/bundle/.ycm_extra_conf.py"
let g:closetag_filenames = "*.html*,*.xhtml,*.phtml,*.erb"
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
